version: '3.1'

services:
  edital:
    build:
      context: .
    ports:
      - 15001:80
    volumes:
      - ./edital:/var/www/html
      - ./vendor:/var/www/vendor

  editaldb:
    image: mariadb:10.8.3
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=editaldb
    links:
      - editaldb
    ports:
      - 15000:80
    volumes:
      - "./phpmyadmin/sessions:/sessions"